LEVEL_PATH = 'levels\\level_03.txt'

# Скорость игрока
PLAYER_SPEED = 3
PLAYER_RECT_X = 30
PLAYER_RECT_Y = 63

# Скорость врагов
COCKROACH_SPEED = 4
COCKROACH_RECT_X = 64
COCKROACH_RECT_Y = 64

LOST_SOUL_SPEED = 1.6
LOST_SOUL_RECT_X = 38
LOST_SOUL_RECT_Y = 64

# Размеры окна
WIN_WIDTH = 800
WIN_HEIGHT = 640
WIN_SIZE = (WIN_WIDTH, WIN_HEIGHT)

# Размеры тайлов
TILE_WIDTH = TILE_HEIGHT = 64
SHADOW_COEF = 2
SHADOW_WIDTH = SHADOW_HEIGHT = TILE_WIDTH // SHADOW_COEF

# Цвета
BLACK = (0, 0, 0)

