
# Размеры окна
WIN_WIDTH = 800
WIN_HEIGHT = 640
WIN_SIZE = (WIN_WIDTH, WIN_HEIGHT)

PLAYER_SPEED = 3
PLAYER_RECT_X = 30
PLAYER_RECT_Y = 63

# Размеры тайлов
TILE_WIDTH = TILE_HEIGHT = 64
SHADOW_COEF = 2
SHADOW_WIDTH = SHADOW_HEIGHT = TILE_WIDTH // SHADOW_COEF
# Цвета
BLACK = (0, 0, 0)
# Группы спрайтов